# docker-compose.yml

version: '3.8'
services:

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pasword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5433'

volumes:
  postgres:
