name: Deploy to Cloud Run from Source for development

on:
  push:
    branches: [ "dev" ]

env:
  PROJECT_ID: nest-docker-run-githubactions
  SERVICE: nest-docker-googlerun-githubactions-dev
  REGION: us-central1
  DATABASE_URL: postgresql://postgres:${{ secrets.EXAMPLEDB_PSWD }}@localhost:5432/exampledb

jobs:
  # deploy:
  #   permissions:
  #     contents: 'read'
  #     id-token: 'write'

  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Google Auth
  #       id: auth
  #       uses: 'google-github-actions/auth@v1'
  #       with:
  #         workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
  #         service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      # - name: Deploy to Cloud Run
      #   id: deploy
      #   uses: google-github-actions/deploy-cloudrun@v1
      #   with:
      #     service: ${{ env.SERVICE }}
      #     region: ${{ env.REGION }}
      #     source: ./        

      # - name: Show Output
      #   run: echo ${{ steps.deploy.outputs.url }}

  migrate:
    permissions:
          contents: 'read'
          id-token: 'write'
          
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: yarn install

      - name: Start Cloud SQL Proxy
        run: |
          wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
          chmod +x cloud_sql_proxy
          ./cloud_sql_proxy -instances=${{ secrets.CLOUD_SQL_CONNECTION_NAME }}=tcp:5432 -credential_file=cloudsql-proxy.json &

      - name: Wait for Cloud SQL Proxy to Start
        run: sleep 5

      - name: Migrate Database
        run: yarn prisma migrate deploy

      - name: Stop Cloud SQL Proxy
        run: pkill cloud_sql_proxy